name: HonoursRun

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Hard clean
        shell: powershell
        run: |
          Remove-Item -Recurse -Force Honours_Project_CompetencyandSkillTracking\bin -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force Honours_Project_CompetencyandSkillTracking\obj -ErrorAction SilentlyContinue
        
      - name: Restore
        run: dotnet restore Honours_Project_CompetencyandSkillTracking/Honours_Project_CompetencyandSkillTracking.sln
      
      - name: Build main project
        run: dotnet build Honours_Project_CompetencyandSkillTracking/Honours_Project_CompetencyandSkillTracking/Honours_Project_CompetencyandSkillTracking.csproj -c Debug
      
      - name: Build tests
        run: dotnet build Honours_Project_CompetencyandSkillTracking/HonoursUnitTests/HonoursUnitTests.csproj -c Debug
      
      - name: Test
        run: dotnet test Honours_Project_CompetencyandSkillTracking/HonoursUnitTests/HonoursUnitTests.csproj -c Debug
