name: HonoursRun
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Restore Solution
        run: dotnet restore

      - name: Build Web Project
        run: dotnet build Honours_Project_CompetencyandSkillTracking -c Debug --no-restore

      - name: Build Tests
        run: dotnet build HonoursUnitTests -c Debug --no-restore

      - name: Run Tests
        run: dotnet test HonoursUnitTests -c Debug --no-build --no-restore
